import type { Story } from "./supabase";

export const mockStories: Story[] = [
  {
    id: "1",
    title: "Through the Valley — How I Found Peace After Loss",
    content: `The phone call came at 3:14 AM on a Tuesday. I remember the exact time because I had been lying awake, somehow sensing that something was about to change. My mother had passed. The woman who sang hymns while cooking, who pressed scripture verses into my palm when I was afraid, who called me her "prayer warrior" — she was gone.\n\nFor months I walked through a fog so thick I could barely breathe. My faith, which had always felt like solid ground beneath my feet, suddenly seemed like sand. I cried out to God in the middle of the night. I asked why. I bargained. I was angry.\n\nBut one morning, about six months after her passing, I sat in her favorite chair — the one by the east window where she used to watch the sunrise — and the light came in differently. It was golden and warm and it filled the whole room. And I heard her voice, not audibly, but in my spirit: "I'm okay, baby. More than okay. Keep standing."\n\nSomething broke open in me that morning. Not broke apart — broke open. Like a seed cracking so something beautiful can grow. I began to see that grief and faith are not opposites. They're companions on the same road. And that road leads somewhere good.\n\nToday I run a grief support group at my local church. I tell every person who walks through the door what my mother taught me: the valley is not the destination. You're just passing through. Keep walking. Keep standing.`,
    excerpt: "The phone call came at 3:14 AM on a Tuesday. I remember the exact time because I had been lying awake, somehow sensing that something was about to change…",
    author_name: "Evelyn M.",
    category: "Loss & Grief",
    image_url: null,
    likes: 142,
    prayers: 89,
    encouragements: 57,
    created_at: "2024-11-15T09:22:00Z",
    is_featured: true,
  },
  {
    id: "2",
    title: "Fifteen Years Sober — Grace Found Me in the Darkest Hour",
    content: `I never thought I'd be someone who shares their story publicly. I spent so many years hiding — in bottles, in excuses, in shame. But I'm fifteen years sober today, and if my words help one person hold on one more day, then every word is worth it.\n\nMy addiction began slowly, as they often do. A drink to relax after work. Two drinks. Then the bottle. Then anything I could get my hands on. I lost my job, my apartment, and almost my life. I sat in a hospital bed after a near-fatal incident, and a nurse — her name was Sandra — sat with me on her break and prayed over me. Just quietly, gently. She didn't ask permission. She just held my hand and spoke life over me.\n\nSomething changed in me that night. Not all at once — recovery isn't a light switch. But a seed was planted. I entered a faith-based recovery program and slowly, painstakingly, I began to rebuild.\n\nFifteen years later I am a counselor in that same program. I am a father, a husband, a man of faith. I am still standing — not by my own strength, but by grace I did nothing to deserve and everything to be grateful for.`,
    excerpt: "I never thought I'd be someone who shares their story publicly. I spent so many years hiding — in bottles, in excuses, in shame…",
    author_name: "Marcus T.",
    category: "Addiction & Recovery",
    image_url: null,
    likes: 203,
    prayers: 167,
    encouragements: 94,
    created_at: "2024-11-10T14:05:00Z",
    is_featured: true,
  },
  {
    id: "3",
    title: "Diagnosed at 34 — What Chronic Illness Taught Me About Strength",
    content: `When the doctor said "multiple sclerosis," the room seemed to tilt. I was 34, running marathons, raising two kids, building a career. I thought I was invincible.\n\nThe years that followed tested every belief I had. There were days I couldn't get out of bed. Days I cried in the shower so my children wouldn't hear. Days I questioned everything — my faith, my future, my purpose.\n\nBut in those stripped-down, raw, impossible moments, I discovered something: God meets you at your lowest. Not with easy answers or instant healing, but with a presence so steady it becomes the ground you stand on when everything else has fallen away.\n\nI learned to celebrate small victories. Getting dressed. Making breakfast. Walking to the mailbox. I found a community of others walking similar roads, and we became each other's strength on the days we had none of our own.\n\nI am still here. Still imperfect. Still in pain some days. But still standing — and standing means everything.`,
    excerpt: "When the doctor said 'multiple sclerosis,' the room seemed to tilt. I was 34, running marathons, raising two kids, building a career…",
    author_name: "Diane K.",
    category: "Health & Healing",
    image_url: null,
    likes: 178,
    prayers: 134,
    encouragements: 72,
    created_at: "2024-11-05T11:30:00Z",
    is_featured: false,
  },
  {
    id: "4",
    title: "From Bankruptcy to Breakthrough — A Financial Resurrection Story",
    content: `Three years ago I filed for bankruptcy. I had built a business, watched it collapse, and found myself six figures in debt with a family to feed. The shame of that season nearly swallowed me whole.\n\nWhat I didn't expect was that hitting rock bottom would become a foundation. When there's nothing left to lose, you find out what you truly believe. For me, that was faith — raw, desperate, sincere faith that God had not abandoned me.\n\nI took a minimum wage job. I tithed even when it didn't make sense. I showed up every day and did the work in front of me, no matter how small it seemed.\n\nSlowly, things shifted. A door opened. Then another. Three years later I run a thriving small business and I teach financial literacy at my church because I know what it feels like when the numbers don't add up and hope feels foolish.\n\nYour story isn't over. The breakthrough is often just one faithful step ahead of where you are.`,
    excerpt: "Three years ago I filed for bankruptcy. I had built a business, watched it collapse, and found myself six figures in debt with a family to feed…",
    author_name: "Raymond O.",
    category: "Financial Breakthrough",
    image_url: null,
    likes: 156,
    prayers: 98,
    encouragements: 88,
    created_at: "2024-10-28T08:15:00Z",
    is_featured: true,
  },
  {
    id: "5",
    title: "Healing the Invisible Wounds — My Journey Through Depression",
    content: `Depression doesn't look the way movies portray it. I was functional. I smiled at work. I showed up for my family. But inside, I was drowning in a grey ocean with no visible shore.\n\nFor years I thought faith meant not struggling. I was wrong. Some of the most faithful people in scripture cried out from pits of despair — David, Elijah, Jeremiah. Their honesty about suffering is in our holiest texts for a reason.\n\nSeeing a therapist was the bravest thing I ever did. Accepting medication was not a failure of faith — it was an act of stewardship over the mind God gave me. Slowly, with professional support and the anchor of my faith community, the grey began to lift.\n\nI'm not "cured." I manage. I watch. I take care of myself. But I have also learned that struggle does not disqualify you from purpose. Sometimes it is the very thing that qualifies you to help others find their way through.`,
    excerpt: "Depression doesn't look the way movies portray it. I was functional. I smiled at work. I showed up for my family. But inside, I was drowning…",
    author_name: "Priya S.",
    category: "Mental Health",
    image_url: null,
    likes: 231,
    prayers: 189,
    encouragements: 112,
    created_at: "2024-10-20T16:45:00Z",
    is_featured: false,
  },
  {
    id: "6",
    title: "Rebuilding After Divorce — Finding Wholeness Again",
    content: `My marriage ended after seventeen years. The life I had built, the identity I had formed, the future I had imagined — all of it unraveled in a matter of months. I was fifty-two years old and starting over.\n\nI won't pretend the process was graceful. I was angry, lost, and more lonely than I had words for. But I held onto one truth like a lifeline: I was not defined by what had broken. I was carried by what could not break.\n\nI began showing up to a small group at my church — reluctantly at first. But those people became my family. They fed me, prayed for me, sat with me in the hard places, and celebrated every tiny sign of forward movement.\n\nTwo years later, I have rebuilt a life I genuinely love. Not the life I planned — something realer, truer, more deeply mine. The breaking was real. The rebuilding is too. And God was present in every single moment of both.`,
    excerpt: "My marriage ended after seventeen years. The life I had built, the identity I had formed, the future I had imagined — all of it unraveled…",
    author_name: "Carol J.",
    category: "Family & Relationships",
    image_url: null,
    likes: 119,
    prayers: 101,
    encouragements: 67,
    created_at: "2024-10-12T13:20:00Z",
    is_featured: false,
  },
];
